imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: parameters.php }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        event_date: "November 7, 2015"
        event_date_iso: "2015-11-07"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - 'FOSUserBundle'
        - 'TwigBundle'
    #java: /usr/bin/java
    # ruby: ~
    filters:
        cssrewrite: ~
        scssphp: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database.driver%"
        host:     "%database.host%"
        port:     "%database.port%"
        dbname:   "%database.name%"
        user:     "%database.user%"
        password: "%database.password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer.transport%"
    host:      "%mailer.host%"
    username:  "%mailer.user%"
    password:  "%mailer.password%"
    spool:     { type: memory }

easy_admin:
    site_name: 'South Dakota Code Camp'
    list_actions: ['show', 'edit']
    entities:
        Speakers:
            class: AppBundle\Entity\Speaker
            list:
                fields: ['id', 'fullName', 'visible']
            edit:
                fields: ['firstName', 'lastName', 'email', 'visible', 'slug', 'bio', 'twitter', 'company', 'companyUrl', 'personalSite', 'sessions']
            new:
                fields: ['firstName', 'lastName', 'email', 'visible', 'slug', 'bio', 'twitter', 'company', 'companyUrl', 'personalSite', 'sessions']
        Sessions:
            class: AppBundle\Entity\Session
            list:
                fields: ['id', 'title', 'speaker']
            edit:
                fields: ['title', 'speaker', 'abstract']
            new:
                fields: ['title', 'speaker', 'abstract']
        SpeakerSubmissions:
            class: AppBundle\Entity\SpeakerSubmission
            list:
                fields: ['id', 'title', 'speaker']
            edit:
                fields: ['name', 'email', 'title', 'abstract', 'bio']
            new:
                fields: ['name', 'email', 'title', 'abstract', 'bio']

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
