services:
    # Admin Services
    admin.speaker:
        class: AppBundle\Admin\SpeakerAdmin
        arguments: [~, AppBundle\Entity\Speaker, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Speaker }

    admin.session:
            class: AppBundle\Admin\SessionAdmin
            arguments: [~, AppBundle\Entity\Session, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Session }

    # Menu
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@app.menu_builder", createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    # Summary
    app.summary.summarizer:
        class: AppBundle\Summary\Summarizer

    # Twig
    app.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        arguments:
            - "@app.summary.summarizer"
        tags:
            - { name: twig.extension }
